title: Simons Notes
description: Big data and coding adventures.

author: Simon Streubel
url: http://simnotes.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
# - title: About
#   url: /about
# - title: Contact
#   url: /contact

defaults:
 -
  scope:
    path: ""
    type: "posts"
  values:
    comments: true

social:
  github: simnotes
  twitter: 
  facebook: simon.espunkt.9
  email: simnotes@gmail.com
  disqus_shortname: simnotes

google_analytics: "UA-64804367-1"

